n = input('Digite algo')
print('O tipo primitivo é: ',type(n))
print('É numerico? ', n.isnumeric())
print('Está em maiusculo? ', n.isupper())
print('É alfabetico? ', n.isalpha())
print('É alfanumérico? ', n.isalnum())